name: Release Latest Python Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional: Python version tag to release (overrides latest detected)'
        required: false
        type: string

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_tag.outputs.latest_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          pip install -r .github/scripts/requirements.txt
      - name: Determine tag to use
        id: get_tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "latest_tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            latest_tag=$(python .github/scripts/get_python_version.py --latest --stable)
            echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          fi

  build-and-release-matrix:
    needs: get-latest-tag
    strategy:
      matrix:
        platform-version: ['24.04', '22.04']
        arch: [ppc64le]
        runner-label: [ubuntu-24.04-ppc64le]
    uses: ./.github/workflows/reusable-build-and-release-python-versions.yml
    with:
      arch: ${{ matrix.arch }}
      tag: ${{ needs.get-latest-tag.outputs.latest_tag }}
      platform-version: ${{ matrix.platform-version }}
      runner-label: ${{ matrix.runner-label }}

  release-asset:
    needs: [build-and-release-matrix, get-latest-tag]
    uses: ./.github/workflows/reusable-release-python-tar.yml
    with:
      tag: ${{ needs.get-latest-tag.outputs.latest_tag }}