name: Release Matching Python Tags

on:
  workflow_dispatch:
    inputs:
      tag_filter:
        description: 'Optional: Filter for Python versions (e.g., 3.13.*). If empty, uses latest.'
        required: false
        type: string

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tags_json: ${{ steps.collect.outputs.tags_json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Get Python tags matching filter
        id: collect
        run: |
          echo "Input tag_filter: '${{ github.event.inputs.tag_filter }}'"

          TAG_FILTER="${{ github.event.inputs.tag_filter }}"
          if [ -z "$TAG_FILTER" ]; then
            LATEST=$(python .github/scripts/get_python_version.py --latest)
            echo "No tag_filter input provided, fetched latest tag: $LATEST"
            FILTER=$(echo "$LATEST" | sed -E 's/\.[0-9]+$/.*/')
          else
            FILTER="$TAG_FILTER"
          fi

          TAGS=$(python .github/scripts/get_python_version.py --list --filter "$FILTER")
          TAGS_JSON=$(echo "$TAGS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "tags_json=$TAGS_JSON" >> "$GITHUB_OUTPUT"

  build-and-release-matrix:
    needs: get-tags
    strategy:
      matrix:
        tag: ${{ fromJson(needs.get-tags.outputs.tags_json) }}
        platform-version: ['24.04']
        arch: [ppc64le]
        runner-label: [ubuntu-24.04-ppc64le]
    uses: ./.github/workflows/reusable-build-and-release-python-versions.yml
    with:
      arch: ${{ matrix.arch }}
      tag: ${{ matrix.tag }}
      platform-version: ${{ matrix['platform-version'] }}
      runner-label: ${{ matrix['runner-label'] }}

  release-assets:
    needs: [build-and-release-matrix, get-tags]
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Loop through tags and trigger release workflow
        env:
          TAGS_JSON: ${{ needs.get-tags.outputs.tags_json }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REUSABLE_WORKFLOW: .github/workflows/reusable-release-python-tar.yml
        run: |
          TAGS=$(echo "$TAGS_JSON" | jq -r '.[]')

          for TAG in $TAGS; do
            echo "Triggering release for tag: $TAG"
            gh workflow run "$REUSABLE_WORKFLOW" -f tag="$TAG"

            # Wait for workflow run to start
            while true; do
              RUN_ID=$(gh run list --workflow "$REUSABLE_WORKFLOW" --json databaseId,displayTitle -q ".[] | select(.displayTitle | test(\"$TAG\")) | .databaseId" | head -n1)
              if [ -n "$RUN_ID" ]; then
                break
              fi
              echo "Waiting for workflow run to be created for tag $TAG..."
              sleep 5
            done

            # Wait for run to finish
            while true; do
              STATUS=$(gh run view "$RUN_ID" --json status -q '.status')
              echo "Status: $STATUS"
              if [[ "$STATUS" == "completed" ]]; then
                CONCLUSION=$(gh run view "$RUN_ID" --json conclusion -q '.conclusion')
                echo "Conclusion: $CONCLUSION"
                if [[ "$CONCLUSION" != "success" ]]; then
                  echo "Release failed for tag $TAG"
                  exit 1
                fi
                break
              fi
              sleep 15
            done
          done
