name: Reusable Release Python Tar

on:
  workflow_call:
    inputs:
      tag:
        description: "Release tag (e.g., 3.13.3)"
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: false

jobs:
  release-assets-and-update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifact
          pattern: python-tar-${{ inputs.tag }}-*
          merge-multiple: true

      - name: List downloaded files (debugging step)
        run: ls -R ./artifact

      - name: Release all .tar.gz files from python-tar
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          files: ./artifact/**/*.tar.gz
          draft: false
          prerelease: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer requests pydantic
        working-directory: .github/scripts

      - name: Download upstream versions-manifest.json
        run: |
          curl -sSL -o versions-manifest.json "https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json"

      - name: Update manifests for all released assets
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          assets_json='${{ steps.create_release.outputs.assets }}'
          asset_count=$(echo "$assets_json" | jq length)

          for i in $(seq 0 $((asset_count - 1))); do
            asset_name=$(echo "$assets_json" | jq -r ".[$i].name")
            download_url=$(echo "$assets_json" | jq -r ".[$i].browser_download_url")

            # Parse asset name: python-tag-linux-platform_version-arch.tar.gz
            base_name="${asset_name#python-}"
            base_name="${base_name%.tar.gz}"

            IFS='-' read -r _ platform platform_version arch <<< "$base_name"

            manifest_file="versions-manifest-${arch}.json"

            # Prepare arch-specific manifest if not exists
            if [ ! -f "$manifest_file" ]; then
              echo "[]" > "$manifest_file"
            fi

            echo "::group::Parsed asset metadata"
            echo "Asset: $asset_name"
            echo "Version: ${{ inputs.tag }}"
            echo "Platform: $platform"
            echo "Platform version: $platform_version"
            echo "Arch: $arch"
            echo "Download URL: $download_url"
            echo "::endgroup::"

            python .github/scripts/manifest_tools.py update_version \
              "$manifest_file" \
              --version "${{ inputs.tag }}" \
              --filename "$asset_name" \
              --arch "$arch" \
              --platform "$platform" \
              --platform-version "$platform_version" \
              --download-url "$download_url" \
              --stable
          done

      - name: Merge all arch-specific manifests into main manifest
        run: |
          for manifest in versions-manifest-*.json; do
            if [[ "$manifest" != "versions-manifest.json" ]]; then
              python .github/scripts/manifest_tools.py merge versions-manifest.json "$manifest" versions-manifest.json
            fi
          done

      - name: Commit and push updated manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add versions-manifest.json versions-manifest-*.json
          git commit -m "Update manifests for tag ${{ inputs.tag }} [skip ci]" || echo "No changes to commit"
          git push
